drop table if exists `crossmatch_tns`;

create table `crossmatch_tns` (
`id` int unsigned auto_increment not null,
`ra` double not null,
`decl` double not null,
`tns_name` varchar(10),
`tns_prefix` varchar(10),
`disc_mag` float,
`disc_mag_filter` varchar(50),
`type` varchar(20),
`z` float,
`hostz` float,
`host_name` varchar(512),
`disc_instruments` varchar(512),
`public` tinyint,
`sender` varchar(50),
`associated_groups` varchar(512),
`classifying_groups` varchar(512),
`discovering_groups` varchar(512),
`class_instrument` varchar(512),
`tnsid` int unsigned,
`disc_int_name` varchar(512),
`ext_catalogs` varchar(512),
`disc_date` datetime,
`tns_at` tinyint,
`htm16` bigint unsigned not null,
PRIMARY KEY `idx_id` (`id`),
KEY `idx_htm16` (`htm16`),
UNIQUE KEY `idx_tns_name` (`tns_name`),
KEY `idx_type` (`type`)
) ENGINE=InnoDB;
