from django.db import models

class Candidates(models.Model):
    objectid = models.CharField(db_column='objectId', max_length=16, blank=True, null=True)  # Field name made lowercase.
    jd = models.FloatField(blank=True, null=True)
    fid = models.IntegerField(blank=True, null=True)
    pid = models.BigIntegerField(blank=True, null=True)
    diffmaglim = models.FloatField(blank=True, null=True)
    pdiffimfilename = models.CharField(max_length=255, blank=True, null=True)
    programpi = models.CharField(max_length=255, blank=True, null=True)
    programid = models.IntegerField(blank=True, null=True)
    candid = models.BigIntegerField(primary_key=True)
    isdiffpos = models.CharField(max_length=255, blank=True, null=True)
    tblid = models.BigIntegerField(blank=True, null=True)
    nid = models.IntegerField(blank=True, null=True)
    rcid = models.IntegerField(blank=True, null=True)
    field = models.IntegerField(blank=True, null=True)
    xpos = models.FloatField(blank=True, null=True)
    ypos = models.FloatField(blank=True, null=True)
    ra = models.FloatField(blank=True, null=True)
    decl = models.FloatField(blank=True, null=True)
    magpsf = models.FloatField(blank=True, null=True)
    sigmapsf = models.FloatField(blank=True, null=True)
    chipsf = models.FloatField(blank=True, null=True)
    magap = models.FloatField(blank=True, null=True)
    sigmagap = models.FloatField(blank=True, null=True)
    distnr = models.FloatField(blank=True, null=True)
    magnr = models.FloatField(blank=True, null=True)
    sigmagnr = models.FloatField(blank=True, null=True)
    chinr = models.FloatField(blank=True, null=True)
    sharpnr = models.FloatField(blank=True, null=True)
    sky = models.FloatField(blank=True, null=True)
    magdiff = models.FloatField(blank=True, null=True)
    fwhm = models.FloatField(blank=True, null=True)
    classtar = models.FloatField(blank=True, null=True)
    mindtoedge = models.FloatField(blank=True, null=True)
    magfromlim = models.FloatField(blank=True, null=True)
    seeratio = models.FloatField(blank=True, null=True)
    aimage = models.FloatField(blank=True, null=True)
    bimage = models.FloatField(blank=True, null=True)
    aimagerat = models.FloatField(blank=True, null=True)
    bimagerat = models.FloatField(blank=True, null=True)
    elong = models.FloatField(blank=True, null=True)
    nneg = models.IntegerField(blank=True, null=True)
    nbad = models.IntegerField(blank=True, null=True)
    rb = models.FloatField(blank=True, null=True)
    ssdistnr = models.FloatField(blank=True, null=True)
    ssmagnr = models.FloatField(blank=True, null=True)
    ssnamenr = models.CharField(max_length=255, blank=True, null=True)
    sumrat = models.FloatField(blank=True, null=True)
    magapbig = models.FloatField(blank=True, null=True)
    sigmagapbig = models.FloatField(blank=True, null=True)
    ranr = models.FloatField(blank=True, null=True)
    decnr = models.FloatField(blank=True, null=True)
    sgmag1 = models.FloatField(blank=True, null=True)
    srmag1 = models.FloatField(blank=True, null=True)
    simag1 = models.FloatField(blank=True, null=True)
    szmag1 = models.FloatField(blank=True, null=True)
    sgscore1 = models.FloatField(blank=True, null=True)
    distpsnr1 = models.FloatField(blank=True, null=True)
    ndethist = models.IntegerField(blank=True, null=True)
    ncovhist = models.IntegerField(blank=True, null=True)
    jdstarthist = models.FloatField(blank=True, null=True)
    jdendhist = models.FloatField(blank=True, null=True)
    scorr = models.FloatField(blank=True, null=True)
    tooflag = models.IntegerField(blank=True, null=True)
    objectidps1 = models.BigIntegerField(blank=True, null=True)
    objectidps2 = models.BigIntegerField(blank=True, null=True)
    sgmag2 = models.FloatField(blank=True, null=True)
    srmag2 = models.FloatField(blank=True, null=True)
    simag2 = models.FloatField(blank=True, null=True)
    szmag2 = models.FloatField(blank=True, null=True)
    sgscore2 = models.FloatField(blank=True, null=True)
    distpsnr2 = models.FloatField(blank=True, null=True)
    objectidps3 = models.BigIntegerField(blank=True, null=True)
    sgmag3 = models.FloatField(blank=True, null=True)
    srmag3 = models.FloatField(blank=True, null=True)
    simag3 = models.FloatField(blank=True, null=True)
    szmag3 = models.FloatField(blank=True, null=True)
    sgscore3 = models.FloatField(blank=True, null=True)
    distpsnr3 = models.FloatField(blank=True, null=True)
    nmtchps = models.IntegerField(blank=True, null=True)
    rfid = models.BigIntegerField(blank=True, null=True)
    jdstartref = models.FloatField(blank=True, null=True)
    jdendref = models.FloatField(blank=True, null=True)
    nframesref = models.IntegerField(blank=True, null=True)
    htmid16 = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'candidates'
        app_label = 'Candidates'

